name: Build & Publish Azure DevOps Extension

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build and package extension
        run: npm run package

      - name: Install tfx-cli
        run: npm install -g tfx-cli

      - name: Publish to Azure DevOps Marketplace
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          PUBLISHER_ID: ${{ secrets.PUBLISHER_ID }}
        run: |
          tfx extension publish \
            --publisher "$PUBLISHER_ID" \
            --manifest-globs vss-extension.json \
            --token "$AZURE_DEVOPS_PAT"
